runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: main.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]

builtins:
- deferred: on
- appstats: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'myapp.settings'

#error_handlers:
#  - file: default_error.html
#  - error_code: over_quota
#    file: over_quota.html

#
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.bak$
- ^(.*/)?\.txt$
- ^(.*/)?\.sql3$
